### ISSUE TITLE
I/O lib doesn't work on some OS (with Love2D, pure Lua has no problems)

### ISSUE THREAD

**Issue by aranval** [YoungNeer/iffy#1]
Hey,
Just letting you know io.open doesn't work for both me and my coprogrammer. We had to replace those functions with love.filesystem.read (or love.filesystem.lines for infile:lines() interations).
Just FYI, we got it handled but you might post a warning or something for other users (it took us a bit of time to figure out)

**Comment by besnoi** [comment]
I am super sorry for the io dependencies - the main reason to use them was because io.read reads file relatively by default whereas love.filesystem.read reads file from the save directory by default. Anyways I'll fix it in the next version (I'll also use spritebatches in the next version for max performance). Thanks for pointing that out and thanks for letting me know.

**Comment by besnoi** [comment]
Fixed all the io dependencies! (_finally_)
